### ISSUE TITLE
ACF 5.8-beta4.1 - ACF Block Duplication bug

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#159]
This bug was introduced with beta 4, and is still not fixed with 4.1. Note that, this bug was NOT present in beta 3, meaning, beta 3 was working fine as far as acf block duplications.

The issue: If you duplicate an ACF block, and make changes to the duplicated blocks, the modifications are ONLY shown in the editor and not on the front end.

I have a 2 minute video, where I duplicate an ACF block and the changes are only shown in the editor, and then I recreate a variation of the block instead of duplicating it, and all is fine:

https://www.youtube.com/watch?v=WpTlVlT0Y54&feature=youtu.be

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the bug report and screen recording.
I'll add this to our list and will report back shortly.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks again for the screen recording. I've just tried to replicate this issue locally, but was unable to find any problem rendering the block front-end.

It is possible that the issue has been fixed in some recent work done on the beta4.1 branch.
I've just updated the plugin files online. Can you please re-download beta 4.1 and let me know if this solves the issue?

**Comment by nick6352683** [comment]
It's 9:21pm Los Angeles time here Elliot... I will have a look tomorrow at noon my time and report back.

Thanks again...

**Comment by nick6352683** [comment]
Sorry for the delay... I just downloaded a fresh copy of beta4.1, and the Duplication bugs still exists, I tested it in a freshly installed WP testing site...

I wish I had better news for this bug Elliot ! I have to revert back to beta3, as this version is the less buggy (for me).

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the replies.

If it's not too much to ask, can you please spin up a fresh WP site in "Local by Flywheel" and try to replicate the issue?
Please keep the default theme active and edit the functions.php file with any extra logic needed.​

​​If you can replicate the issue, please export the site (from flywheel app, right click the site and click "export") and attach to your next reply.
​I'll import this and get to work replicating / testing the issue :)

**Comment by nick6352683** [comment]
Hi Elliot, thanks for the reply. I did create a fresh local  WP site, and duplicated the "duplicate" issue with beta4 - 4.1. Because I don't want to publish the links to my files, is there an email address where I can send you the links? If you don't want to publish your email address, please email me at nick6352683@yhoo.com.

Thanks.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for replicating the issue using Local. The best way to send those files will be via the ACF contact form: https://www.advancedcustomfields.com/contact/

* Ask for me, Elliot, in the comment and the team will forward it to me :)

**Comment by nick6352683** [comment]
Closing this and opening new one with better explanations and with testing ACF 5.8 RC2...
