### ISSUE TITLE
ACF Pro 5.8.1: Wysiwyg Editor content disappearing on reorder (Block)

### ISSUE THREAD

**Issue by christophery** [AdvancedCustomFields/acf#191]
I've been playing around the new ACF blocks feature in 5.8.1 and noticed that the content in the Wysiwyg Editor field will disappear (visual editor) when you reorder the custom block downwards (seems to be fine reordering up).

The content in the Wysiwyg Editor field is still saved on update + reload of the page but only seems to be gone in the visual editor.

I'm using WordPress 5.2.1 and ACF Pro 5.8.1 with a barebones [underscores](https://underscores.me/) theme enabled. No additional plugins are enabled but ACF Pro.

### Steps to reproduce:

1. Create a new block using `acf_register_block`.
2. Create a template for the block render callback.
3. Add a **Wysiwyg Editor field** and assign it to your new block.
4. Add your new block with the Wysiwyg Editor field to a page/post.
5. Add some content to the Wysiwyg Editor field.
6. Reorder the block **down** (using the arrows on the left).

![Untitled](https://user-images.githubusercontent.com/1683361/59057560-a18f2500-8868-11e9-931b-3b62f69e48d4.gif)

**Comment by elliotcondon** [comment]
Hi @christophery 

Thanks for the bug report + screen recording.

This issue matches one that I opened with the Gutenberg developers here:
https://github.com/WordPress/gutenberg/issues/15243

Unfortunately, I am not yet able to fix this from my end, and am waiting to hear back from Gutenberg developers.

**Comment by laloptk** [comment]
Yeah, Same issue here.

**Comment by kanlukasz** [comment]
I have same problem.

My example:
![stream3](https://user-images.githubusercontent.com/30685349/76326437-ec9f0280-62e8-11ea-845c-a3e50529e078.gif)

**Comment by elliotcondon** [comment]
Hi @kanlukasz 

The status of this issue remains unsolved. I received some good advice from ticket 15243, which I'm hoping to implement in an upcoming release. There is unfortunately no fix for the time being.

**Comment by kanlukasz** [comment]
Hi @elliotcondon 

Thank you for checking the status of the problem.
I hope this will be fixed in the next version because I can't implement an important thing on my clients' pages because of this.

**Comment by GitFrankie** [comment]
Same issue, chiming in to say I would appreciate a fix. Makes for a buggy admin experience for my clients. Telling them to save after reordering, close page/post, and open back up brings back the text but is hacky. Otherwise I love this plugin so much!

**Comment by elliotcondon** [comment]
Hi all 👋. Good news to report, I've implemented a fix for this issue in our 5.9 build!
Version 5.9.0-beta4 is scheduled for release tomorrow, with the final build planned for ~3 weeks time.

**Comment by christophery** [comment]
Hi @elliotcondon,

This issue seems to still persist if the ACF block is nested within another block (ie: Group, Columns).

I've tested this with WordPress 5.7.2 and ACF Pro 5.9.3. No additional plugins are enabled but ACF Pro.

### Steps to reproduce:

1.  Create a new block using `acf_register_block`.
2.  Add a Wysiwyg Editor field and assign it to your new block.
3.  Add your new block within another block (nesting) like **group** or **columns**. 
`(ie: Document > Columns > Column > My Test Block)`
4.  Add some content to the Wysiwyg Editor field.
5.  Reorder the block down (using the arrows on the top).

![acf-block-test](https://user-images.githubusercontent.com/1683361/118294165-724bae80-b4a8-11eb-996c-5e42bc4f4834.gif)

**Comment by christophery** [comment]
Issue is fixed in 5.9.6, thanks!
