### ISSUE TITLE
5.9 beta - Convert WYSIWYG content to innerBlocks

### ISSUE THREAD

**Issue by JiveDig** [AdvancedCustomFields/acf#323]
I have an ACF block heavily used on a few large sites. I'd like to update the block to only use innerBlocks in place of an existing WYSIWG field. Trying to figure out a way to `get_field( 'my_content' )` and pass that to the innerBlocks (or some version of that) the next time the post/page is edited.

**Comment by elliotcondon** [comment]
Hi @JiveDig 

Great question. I'm not exactly sure how this would be possible, but I'll start searching for a solution 👍

**Comment by JiveDig** [comment]
I started testing passing the existing value to the template, only if there is an existing value. Didn’t get it to work, but that would still require the “old” field to be registered so it works with get_field(). Another layer or difficulty is that the old field won’t be available anymore since it’s now just using innerBlocks.

**Comment by JiveDig** [comment]
Still not able to to do this. Tried a few ways and got stuck. I'm thinking the only solution may be to leave the _old_ field registered but hide it via conditional logic that is always `false`, then `load_field` filter to check for that value or something like that. It'd get tricky though as we'd need to clear the old field value on save of the new field.

**Comment by elliotcondon** [comment]
Yep, this is a tricky one indeed. I've still got this on my to-do for RC2, but haven't looked into it just yet.

**Comment by JiveDig** [comment]
Just to update: I released an update to my plugin which now uses InnerBlocks. 

Here's the logic:

- If a block has content in the old WYSIWYG field, it still displays (along with any new content in the InnerBlocks).
- The editor shows a notice that there is old content, and recommends you copy/paste it into the inner block editor. I tried a ton of things and couldn't get it to load the content into the InnerBlocks :(
- I have a conditional (if no old content) in `acf/prepare_field` filter which then hides the old field once content is cleared, or for new instances.

I'd love a way that didn't require copy/paste or leaving the old field registered, but this solution is working as of now.

<img width="1692" alt="Markup 2020-09-02 at 13 57 00" src="https://user-images.githubusercontent.com/540990/92019180-33b00280-ed24-11ea-8317-64b0c96da2f1.png">

**Comment by elliotcondon** [comment]
Hi @JiveDig. Great work! 

I agree. An automated solution for setting the InnerBlocks content would be ideal. 
I still have this on my to-do list for the 5.9 version and hope to find a solution in the future.

For now, I'm glad you have a working update 👍.

P.S. Can you remind me of the plugin you are working on? I've lost track, sorry.

**Comment by JiveDig** [comment]
Thanks Elliot. Still super excited for inner blocks. I have a few things I need to convert/update, but this one took priority. It's a GitHub-only plugin as of now https://github.com/maithemewp/mai-notices
