### ISSUE TITLE
Version 5.9 savePost() hotfix

### ISSUE THREAD

**Issue by elliotcondon** [AdvancedCustomFields/acf#373]
### Description
The recent ACF 5.9 release contains a bug causing various issues surrounding the saving and previewing of posts. This bug stems from our JS solution to enable AJAX validation for metaboxes whilst an official API is provided.

In this solution, we wrap the core `savePost()` function in our own logic. Our mistake was to ignore the specific return type (a Promise object) of this function, which we have now fixed 👍.

### Solution
Please download and replace the following two JS files found in the [hotfix/version-5-9-savepost](https://github.com/AdvancedCustomFields/acf/tree/hotfix/version-5-9-savepost) branch:
1. /assets/js/acf-input.js
2. /assets/js/acf-input.min.js

### Testing
Please provide feedback via the comments section below, so we can roll out an update as quickly as possible. 

Thanks from the ACF team.

**Comment by jcaren** [comment]
Tested on one site but still having the issue after replacing these 2 files and flushing cache.

**Comment by blogtutor** [comment]
Tested to fix the issue I reported in #374 and it **does** fix it on my test site.

**Comment by FriendlyWP** [comment]
I have tested on localhost and a staging server and the fix is working for me. Thank you!

**Comment by AvitaHealthSystem** [comment]
Tested on my dev site and it appears to have fixed the issue! :)

**Comment by CreativeDive** [comment]
@elliotcondon Is this already fixed in the latest 5.9 version, which is available for download?

**Comment by fastlinemedia** [comment]
Hey @elliotcondon, thanks for jumping on this fix so quickly! I tested on our end and it looks like this fixes the error but the `savePost` promise never resolves. So we still can't fire off any code after a post saves. Here's an example of how we're using it....

```
editor.savePost().then( () => {
	console.log( 'here' )
} )
```

Let me know what you think.

**Comment by elliotcondon** [comment]
Thanks @fastlinemedia. I'll keep working on this and will be in touch shorty.

**Comment by elliotcondon** [comment]
@CreativeDive Not yet. We're aiming for a 5.9.1 release later this week.

**Comment by elliotcondon** [comment]
@CreativeDive @fastlinemedia I've just pushed an update to address the Promise issue. 
Can you please test this out when next possible?

I'm happy with this fix, but would like to check that our Promise `resolve()` and `reject()` functions are passing parameters that match WP core. @fastlinemedia Are you checking any parameters in your chained `then()` callbacks?

**Comment by Pross** [comment]
Hi @elliotcondon 

Justin is away for a couple of days and asked if I could test the fix you mentioned. Where did you push the new fix to test? Your hotfix branch only has the one commit from 8 days ago?

**Comment by elliotcondon** [comment]
@Pross Apologies for that. I hadn't updated the public repo branch. I've just pushed an update to the hotfix now, can you try once more?

**Comment by Pross** [comment]
> @Pross Apologies for that. I hadn't updated the public repo branch. I've just pushed an update to the hotfix now, can you try once more?

Happy to report everything is working as expected now :)
