### ISSUE TITLE
Only Preview mode is available in WP 6.5beta1

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#896]
I just started testing ACF Blocks with WP 6.5 beta1. It seems that they brought the Site Editor experience in the Block Editor, where ACF Blocks are only displayed in Preview mode. The Edit and Auto modes do not work, as they never did in the Site Editor.

Since the Site Editor was merged in the core (WP v5.9 I believe) I was patiently waiting for this to be fixed. Instead, this issue now is ported to the actual Block Editor, which ACF blocks will lose a major advantage over any other type of blocks created other than ACF.

**Comment by mattgrshaw** [comment]
Thanks for the report @nick6352683.

We've noticed this in the beta as well and are looking into this further.

**Comment by nick6352683** [comment]
Thank you very much @mattgrshaw.

**Comment by mattgrshaw** [comment]
This should be fixed in WP 6.5-beta3 which was released today.

**Comment by nick6352683** [comment]
I saw your response to a similar issue yesterday, I just updated my test site to beta 3, and I can confirm that this issue has been fixed.

A similar issue still persists in the Site Editor, but that is not as important...

Thanks.

**Comment by nick6352683** [comment]
@mattgrshaw , I just want to bring this to your attention right now. Just tested WP 6.5RC2 released just a few hours ago, and all is fine...

However, by activating the Gutenberg plugin this bug reappears, which probably means that we will have to revisit this again with WP 6.6 unless they permanently find an acceptable solution before WP 6.6 is released.

**Comment by mattgrshaw** [comment]
Thanks for the heads up @nick6352683. It looks like the current version of the Gutenberg plugin is 17.8.2, which doesn't yet have the fix.

The [PR](https://github.com/WordPress/gutenberg/pull/59105) containing the fix is set for Gutenberg 17.9, so I'm assuming that release will have the fix as well. It has also been backported to the RCs/core, so I think we're OK here.

In any case, the function that ACF was relying on here is being deprecated, so we'll likely update things on our end sooner rather than later.
